Repository MogakGround/Mogak-Server, pull requests merged in 2025-02, with the labels that each got.

#11 [feat] 랭킹 기능 - 낙관적 락 + rabbitmq 추가
  build.gradle
  src/main/java/com/example/mogakserver/auth/application/service/AuthService.java
  src/main/java/com/example/mogakserver/common/config/rabbitMQ/RabbitMqConfig.java
  src/main/java/com/example/mogakserver/common/config/redis/RedisConfig.java
  src/main/java/com/example/mogakserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/mogakserver/external/redis/RedisMessageSubscriber.java
  src/main/java/com/example/mogakserver/external/redis/RedisService.java
  src/main/java/com/example/mogakserver/external/socket/WebRtcWebSocketHandler.java
  src/main/java/com/example/mogakserver/external/socket/service/ScreenShareService.java
  src/main/java/com/example/mogakserver/external/socket/service/TimerService.java
  src/main/java/com/example/mogakserver/ranking/domain/entity/Ranking.java
  src/main/java/com/example/mogakserver/user/api/controller/UserController.java
  src/main/java/com/example/mogakserver/user/application/response/RankingDTO.java
  src/main/java/com/example/mogakserver/user/application/response/RankingListDTO.java
  src/main/java/com/example/mogakserver/user/application/service/UserRankingConsumer.java
  src/main/java/com/example/mogakserver/user/application/service/UserRankingScheduler.java
  src/main/java/com/example/mogakserver/user/application/service/UserService.java
  src/main/java/com/example/mogakserver/user/domain/entity/User.java
  src/main/java/com/example/mogakserver/user/infra/repository/JpaUserRepository.java
Labels: 🚀 Feat

#16 [feat] 중복 검사 기능 구현
  src/main/java/com/example/mogakserver/common/exception/enums/ErrorCode.java
  src/main/java/com/example/mogakserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/mogakserver/room/api/controller/RoomRetrieveController.java
  src/main/java/com/example/mogakserver/room/application/service/RoomRetrieveService.java
  src/main/java/com/example/mogakserver/room/infra/repository/JpaRoomRepository.java
  src/main/java/com/example/mogakserver/user/api/controller/UserController.java
  src/main/java/com/example/mogakserver/user/application/service/UserService.java
  src/main/java/com/example/mogakserver/user/infra/repository/JpaUserRepository.java
Labels: 🚀 Feat

#17 [feat] 마이페이지 화면 기능 구현
  .DS_Store
  .gitignore
  src/main/java/com/example/mogakserver/common/exception/enums/ErrorCode.java
  src/main/java/com/example/mogakserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/mogakserver/room/api/controller/RoomController.java
  src/main/java/com/example/mogakserver/room/api/request/RoomRequestDTO.java
  src/main/java/com/example/mogakserver/room/api/request/RoomUpdateDTO.java
  src/main/java/com/example/mogakserver/room/application/dto/TimerDTO.java
  src/main/java/com/example/mogakserver/room/application/service/RoomRetrieveService.java
  src/main/java/com/example/mogakserver/room/application/service/RoomService.java
  src/main/java/com/example/mogakserver/room/infra/repository/JpaRoomRepository.java
  src/main/java/com/example/mogakserver/roomimg/infra/repository/JpaRoomImgRepository.java
  src/main/java/com/example/mogakserver/roomuser/api/controller/RoomUserController.java
  src/main/java/com/example/mogakserver/roomuser/application/response/MyPageUserRoomDTO.java
  src/main/java/com/example/mogakserver/roomuser/application/response/MyPageUserRoomsListDTO.java
  src/main/java/com/example/mogakserver/roomuser/application/service/RoomUserService.java
  src/main/java/com/example/mogakserver/roomuser/infra/repository/JpaRoomUserRepository.java
  src/main/java/com/example/mogakserver/user/api/controller/UserController.java
  src/main/java/com/example/mogakserver/user/api/request/UpdateProfileRequestDTO.java
  src/main/java/com/example/mogakserver/user/application/response/MyProfileResponseDTO.java
  src/main/java/com/example/mogakserver/user/application/service/UserService.java
  src/main/java/com/example/mogakserver/user/domain/entity/User.java
  src/main/java/com/example/mogakserver/worktime/infra/repository/JpaWorkTimeRepository.java
Labels: 🚀 Feat

#20 [feat] 타이머 스케줄러 구현
  src/main/java/com/example/mogakserver/room/api/controller/RoomRegisterController.java
  src/main/java/com/example/mogakserver/room/application/service/RoomRegisterService.java
  src/main/java/com/example/mogakserver/user/application/service/UserTimerScheduler.java
  src/main/java/com/example/mogakserver/user/domain/entity/User.java
Labels: 🚀 Feat

#21 [feat]방 들어가기, 방 나가기 기능 구현
  src/main/java/com/example/mogakserver/common/config/redis/RedisConfig.java
  src/main/java/com/example/mogakserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/mogakserver/external/socket/WebRtcWebSocketHandler.java
  src/main/java/com/example/mogakserver/roomuser/api/controller/RoomUserController.java
  src/main/java/com/example/mogakserver/roomuser/api/request/RoomEnterRequestDTO.java
  src/main/java/com/example/mogakserver/roomuser/application/response/RoomEnterResponseDTO.java
  src/main/java/com/example/mogakserver/roomuser/application/service/RoomUserService.java
  src/main/java/com/example/mogakserver/roomuser/infra/repository/JpaRoomUserRepository.java
Labels: 🚀 Feat

#24 [test] 방 들어가기 테스트 코드 작성
  build.gradle
  src/test/java/com/example/mogakserver/room/application/RoomServiceTest.java
Labels: 📁 Test

#25 [refactor] 유저 로직 리팩토링
  src/main/java/com/example/mogakserver/auth/api/controller/AuthController.java
  src/main/java/com/example/mogakserver/auth/api/request/LoginRequestDTO.java
  src/main/java/com/example/mogakserver/auth/api/request/SignUpRequestDTO.java
  src/main/java/com/example/mogakserver/auth/api/request/SignUpRequestDto.java
  src/main/java/com/example/mogakserver/auth/api/request/TokenRequestDTO.java
  src/main/java/com/example/mogakserver/auth/api/request/TokenRequestDto.java
  src/main/java/com/example/mogakserver/auth/application/response/LoginResponseDto.java
  src/main/java/com/example/mogakserver/auth/application/service/AuthService.java
  src/main/java/com/example/mogakserver/external/kakao/service/KakaoSocialService.java
  src/main/java/com/example/mogakserver/external/kakao/service/SocialService.java
  src/main/java/com/example/mogakserver/roomimg/domain/entity/RoomImg.java
  src/main/java/com/example/mogakserver/roomimg/domain/entity/RoomImgType.java
  src/main/java/com/example/mogakserver/roomuser/infra/repository/JpaRoomUserRepository.java
  src/main/java/com/example/mogakserver/user/domain/entity/User.java
Labels: 🚀 Feat, 🧠 Refactor

#27 [feat] 유저 로직 수정
  src/main/java/com/example/mogakserver/auth/api/controller/AuthController.java
  src/main/java/com/example/mogakserver/auth/api/request/SignUpRequestDTO.java
  src/main/java/com/example/mogakserver/auth/application/response/LoginResponseDto.java
  src/main/java/com/example/mogakserver/auth/application/service/AuthService.java
  src/main/java/com/example/mogakserver/common/exception/enums/ErrorCode.java
  src/main/java/com/example/mogakserver/common/exception/enums/SuccessCode.java
  src/main/java/com/example/mogakserver/external/kakao/service/KakaoSocialService.java
  src/main/java/com/example/mogakserver/external/kakao/service/SocialService.java
  src/main/java/com/example/mogakserver/user/domain/entity/User.java
Labels: 🚀 Feat

#29 [fix] 유저 로직 수정
  src/main/java/com/example/mogakserver/auth/application/service/AuthService.java
  src/main/java/com/example/mogakserver/user/domain/entity/User.java
Labels: 🔨 Fix

#31 [fix] 유저 로직 수정
  src/main/java/com/example/mogakserver/auth/api/controller/AuthController.java
  src/main/java/com/example/mogakserver/auth/api/request/SignUpRequestDTO.java
  src/main/java/com/example/mogakserver/auth/application/response/LoginResponseDto.java
  src/main/java/com/example/mogakserver/auth/application/service/AuthService.java
  src/main/java/com/example/mogakserver/common/exception/enums/ErrorCode.java
  src/main/java/com/example/mogakserver/common/exception/enums/SuccessCode.java
Labels: 🔨 Fix
